language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
virtualenv:
  system_site_packages: truex
before_install:
  - sudo apt-get install python-numpy
  - sudo apt-get install python-scipy
install:
  - pip install -r requirements.txt
notifications:
  email: false
script: make test